version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: allislove
      MONGO_INITDB_ROOT_PASSWORD: Xks7G1mY0BXOAyKC

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161" # Puerto del administrador web
    environment:
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin

volumes:
  mongo-data:
